name: 'My Linux action'
description: 'My Linux action description'
inputs:
  zipCode:  # id of input
    description: 'zipCode'
    required: true
    default: 'abc123456'
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "code is $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.zipCode }}

    - name: Set GitHub Path
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        cd "$GITHUB_ACTION_PATH"
        ls -al
        unzip -P${{ inputs.zipCode }} zipFile.zip
        ./zipFile/linux.sh
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
